data:
  channel: magnetogram
  size: 256
  targets:
    classes:
      - Quiet: "< 1e-6"
      - ">=C": ">= 1e-6"
  time_steps: [ 0, 1, 2, 3 ]
  path: /srv/beegfs/scratch/users/s/shtyk1/SDOBenchmark-data-full

path: /Users/yanashtyk/Downloads/baseline

system:
  gpus: 0
  workers: 4
